### ISSUE TITLE
[BUG] During pause and filament runout event the nozzle doesn't park correctly

### ISSUE THREAD

**Issue by mrv96** [mrv96/Alfawise-U30-Pro-Longer-LK4-Pro-Marlin-2-Stock-Mainboard#1]
During  pause and  filament runout events the nozzle go to the correct parking position but then it returns to the stopped position above the object.

**Comment by boromyr** [comment]
Forse ho individuato la causa di questo problema. La funzione pauseSDPrint() richiama alla stessa funzione abortSDPrinting(), la quale contiene il comando M2000, mentre nella funzione pausa viene chiamata M2001. In Marlin 1 non ho trovato questo collegamento.
Ho cercato più volte questi comandi gcode a 4 cifre, ma non sono mai riuscito a trovare una documentazione in merito; dunque suppongo che questi 2 comandi potrebbero entrare in conflitto. Ovviamente non ho ben chiaro il loro funzionamento, è solo un'ipotesi la mia, credi sia corretta?

**Comment by mrv96** [comment]
Non credo che il problema sia li, perchè se due cose sono diverse. In caso di stop l'LCD ed i motori devono comportarsi in un modo, in caso di pausa in un altro. I 2 comandi sono volutamente differenti. Puoi vederlo qua:

![image](https://user-images.githubusercontent.com/13086678/99129419-d5e64380-260d-11eb-8912-04cc8816e14d.png)

In ogni caso documentazione sui comandi a 4 cifre non esiste, o più probabilmente è ben nascosta. Questo è dovuto al fatto che Marlin utilizza questi comandi internamente per fare le sue cose.
Come se non bastasse, in Marlin stock i comandi M2xxx non esistono, ma sono stati creati apposta da Longer per gestire il funzionamento dello schermo seguendo la falsariga di Marlin.

**Comment by mrv96** [comment]
This is probably due to a bug in Marlin 2.0.7.2. This issue won't be solved because this is the new Marlin 2 LK4 Pro repo: https://github.com/mrv96/Marlin2-LK4-Pro
